"""Tests for the waste classifiers.

Weighted deliberately toward two things rather than toward coverage.

**The refusals.** A rule that fires when it should not is worse than a rule
that does not exist, because the report is read as a recommendation. So the
cases where the right answer is "leave this alone" get as much room here as the
cases where something is found.

**The three bugs that a real repository found and reasoning did not.** Each has
a regression test below, named for what actually went wrong. All three came
from pointing the tool at one messy JavaScript repository, and none of them
would have been caught by a fixture written from the rule's description --
which is itself the argument for running the thing against real input before
believing it.
"""

import pytest

from contextcost.classify import (
    LARGE_DATA_TOKENS,
    MIN_REPORTABLE_TOKENS,
    RULES,
    by_rule,
    classify,
    rule_named,
)
from contextcost.walk import walk_repository


def build(root, files):
    """Write ``{relative path: text}`` under ``root`` and walk it."""
    for relative, text in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return walk_repository(str(root))


def found(root, files):
    """``{path: rule name}`` for one synthetic repository."""
    return {f.path: f.rule.name for f in classify(build(root, files))}


#: Long enough to clear MIN_REPORTABLE_TOKENS without being interesting.
FILLER = "The quick brown fox jumps over the lazy dog. " * 20


def test_a_lockfile_is_recognised_by_name(tmp_path):
    assert (
        found(tmp_path, {"package-lock.json": FILLER})["package-lock.json"]
        == "lockfile"
    )


def test_every_known_lockfile_name_is_matched(tmp_path):
    names = [
        "yarn.lock",
        "poetry.lock",
        "Cargo.lock",
        "go.sum",
        "uv.lock",
        "Gemfile.lock",
    ]
    result = found(tmp_path, dict.fromkeys(names, FILLER))
    assert set(result) == set(names)
    assert set(result.values()) == {"lockfile"}


def test_a_generator_banner_is_recognised(tmp_path):
    text = "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + FILLER
    assert found(tmp_path, {"api.pb.go": text})["api.pb.go"] == "generated"


def test_prose_containing_the_word_generated_is_not_treated_as_generated(tmp_path):
    """Regression. The marker was the bare substring `generated file`, which
    matched inside "chatgpt-generated files" in a hand-written notices file --
    a false positive at `certain` confidence, which is the worst thing this
    module can produce. Word boundaries and no bare "generated" now.
    """
    text = (
        "# Third party notices\n\nThis project reviews chatgpt-generated files.\n"
        + FILLER
    )
    assert "THIRD_PARTY_NOTICES.md" not in found(
        tmp_path, {"THIRD_PARTY_NOTICES.md": text}
    )


def test_a_banner_far_below_the_top_is_not_a_banner(tmp_path):
    """Regression. Generators write their banner at the very top; that is the
    point of it. Text mentioning "do not edit" thirty lines into a document is
    prose, and searching the whole header for it was how the false positive
    above got its chance.
    """
    text = "\n".join(
        f"Line {n} of ordinary documentation prose here." for n in range(30)
    )
    text += "\nPlease do not edit the section above by hand.\n" + FILLER
    assert "CONTRIBUTING.md" not in found(tmp_path, {"CONTRIBUTING.md": text})


def test_the_evidence_quotes_the_marker_it_matched(tmp_path):
    """Regression. The evidence took the first 90 characters of the matching
    line, so a marker sitting past that cutoff produced a quotation with no
    marker visible in it -- which looks checkable and is not.
    """
    padding = "x" * 120
    text = f"// {padding} @generated by the build\n" + FILLER
    findings = classify(build(tmp_path, {"thing.js": text}))
    assert len(findings) == 1
    assert "@generated" in findings[0].evidence.lower()


def test_minified_by_name_is_separate_from_dense_by_measurement(tmp_path):
    """Regression. Both used to report as `minified`, but that word asserts a
    readable original exists elsewhere -- false for the JSON manifests the
    measurement fires on. A true conclusion with a false reason is exactly what
    the confidence tiers exist to prevent.
    """
    dense = "".join(f"{n:064x}" for n in range(40))
    result = found(tmp_path, {"app.min.js": FILLER, "MANIFEST.json": dense})
    assert result["app.min.js"] == "minified"
    assert result["MANIFEST.json"] == "dense"
    assert rule_named("minified").confidence == "certain"
    assert rule_named("dense").confidence == "likely"


def test_vendored_and_build_and_snapshot_directories(tmp_path):
    result = found(
        tmp_path,
        {
            "vendor/lib/thing.py": FILLER,
            "dist/app.js": FILLER,
            "tests/__snapshots__/view.snap": FILLER,
        },
    )
    assert result["vendor/lib/thing.py"] == "vendored"
    assert result["dist/app.js"] == "build-output"
    assert result["tests/__snapshots__/view.snap"] == "snapshot"


def test_a_large_data_file_is_possible_and_never_certain(tmp_path):
    """The rule the file system cannot settle. In a web app a large CSV is
    waste; in an analysis repository it is the subject. `possible` is what
    keeps `reduce` from deciding that on the user's behalf.
    """
    rows = "".join(f"{n},alpha,beta,gamma,delta,epsilon,zeta\n" for n in range(1500))
    findings = classify(build(tmp_path, {"data/rows.csv": rows}))
    assert [f.rule.name for f in findings] == ["large-data"]
    assert findings[0].rule.confidence == "possible"
    assert findings[0].tokens >= LARGE_DATA_TOKENS


def test_a_small_data_file_is_left_alone(tmp_path):
    """Below the threshold there is nothing to save and a line in the report
    costs the reader more than the file costs the model."""
    assert found(tmp_path, {"config/small.json": '{"a": 1}\n'}) == {}


def test_ordinary_source_is_not_waste(tmp_path):
    source = "def add(a, b):\n    return a + b\n" * 30
    assert found(tmp_path, {"src/pkg/math.py": source, "README.md": FILLER}) == {}


def test_a_file_matches_at_most_one_rule(tmp_path):
    """Several rules fire on `vendor/lib.min.js`. Reporting it once is what
    keeps the totals from being inflated by double counting."""
    findings = classify(build(tmp_path, {"vendor/lib.min.js": FILLER}))
    assert len(findings) == 1
    assert findings[0].rule.name == "minified"


def test_findings_below_the_reporting_floor_are_dropped(tmp_path):
    findings = classify(build(tmp_path, {"go.sum": "a\n"}))
    assert findings == []
    assert MIN_REPORTABLE_TOKENS > 0


def test_findings_are_ranked_by_cost_not_by_category(tmp_path):
    """The report's job is to put the expensive decision first."""
    findings = classify(
        build(
            tmp_path,
            {
                "yarn.lock": FILLER,
                "vendor/big.py": FILLER * 8,
                "dist/mid.js": FILLER * 3,
            },
        )
    )
    assert [f.path for f in findings] == ["vendor/big.py", "dist/mid.js", "yarn.lock"]


def test_grouping_puts_the_most_confident_rules_first(tmp_path):
    grouped = by_rule(
        classify(
            build(
                tmp_path,
                {
                    "data/rows.csv": "n,v\n" + "1,alpha beta gamma\n" * 3000,
                    "go.sum": FILLER,
                },
            )
        )
    )
    assert list(grouped) == ["lockfile", "large-data"]


def test_every_rule_states_a_rationale_someone_could_disagree_with():
    """A rule whose reason cannot be written down does not belong in the set:
    the report's only defence against being wrong is that the reader can check
    it."""
    for rule in RULES:
        assert rule.confidence in {"certain", "likely", "possible"}
        assert len(rule.rationale) > 60
        assert rule.rationale.rstrip().endswith((".", "!"))


def test_an_unknown_rule_name_raises(tmp_path):
    with pytest.raises(KeyError):
        rule_named("no-such-rule")


# --- Windows path-separator audit --------------------------------------------
#
# Every rule in this module consumes a *relative* path that arrives joined
# with "/" -- walk_repository normalises ``os.sep`` away before any rule sees
# a path, and the ignore matcher is compiled over "/"-joined paths too. This
# audit pins that contract by feeding every rule a path that was *not*
# normalised: the backslash form an ``os.sep``-joined walk would produce if a
# producer ever stopped converting. What may be asserted splits by rule class,
# because the two classes read paths differently:
#
# **Directory rules** (vendored, snapshot-dir, build-output) split on "/"
# only (:func:`classify._segments`), so a backslash hides every directory and
# the rule must not fire. That holds on every platform.
#
# **Name rules** (lockfile, minified, snapshot-ext) and the large-data rule
# go through :func:`os.path.basename`, which follows the host: on Windows it
# splits on both separators, on POSIX only on "/". Their verdict for an
# out-of-contract path is therefore platform-defined by construction -- what
# must hold everywhere is only that the rule decides without crashing and
# quotes evidence, never raising or returning a finding whose evidence does
# not name its own rule's reason.
#
# Either way nothing reaches a user: the walker always emits "/", so these
# tests exist so that assumption is checked rather than folklore. They run on
# every platform, so CI's Linux runner exercises them too.

import ntpath  # noqa: E402

import os  # noqa: E402

from contextcost.classify import (  # noqa: E402
    BUILD_OUTPUT,
    LARGE_DATA,
    LARGE_DATA_TOKENS,
    LOCKFILE,
    MINIFIED,
    MIN_REPORTABLE_TOKENS,
    SNAPSHOT,
    VENDORED,
    _segments,
    classify,
)
from contextcost.walk import FileCost, WalkResult  # noqa: E402

#: A token count safely above MIN_REPORTABLE_TOKENS, for hand-built FileCost
#: objects that skip the walk.
FILLER_TOKEN_COUNT = 400


def finding_for(cost):
    """The single rule that fires for one hand-built FileCost, or None."""
    findings = classify(_result_of_one(cost))
    assert len(findings) <= 1
    return findings[0] if findings else None


def _result_of_one(cost):
    return WalkResult(root=".", files=[cost])


#: Directory-based rules: the segment scan sees no directory in a backslash
#: path, so none of these may fire -- on Windows, POSIX, anywhere.
DIRECTORY_CASES = [
    ("vendored", VENDORED, FileCost("vendor\\lib.py", 400, FILLER_TOKEN_COUNT, "code")),
    (
        "snapshot-dir",
        SNAPSHOT,
        FileCost(
            "tests\\__snapshots__\\a.py", 400, FILLER_TOKEN_COUNT, "code"
        ),
    ),
    (
        "build-output",
        BUILD_OUTPUT,
        FileCost("build\\out.py", 400, FILLER_TOKEN_COUNT, "code"),
    ),
]


@pytest.mark.parametrize(
    "name,rule,cost", DIRECTORY_CASES, ids=[c[0] for c in DIRECTORY_CASES]
)
def test_a_backslash_hides_directories_from_directory_rules(name, rule, cost):
    assert _segments(cost.path) == []
    assert finding_for(cost) is None


#: Name-based and measurement rules: the decision is platform-defined for an
#: out-of-contract path, so the portable assertion is "decides without
#: crashing", and where it does fire the evidence quotes the file itself.
NAME_CASES = {
    "lockfile": (
        LOCKFILE,
        FileCost("vendor\\package-lock.json", 400, 400, "code"),
    ),
    "minified": (
        MINIFIED,
        FileCost("dist\\app.min.js", 4000, 4000, "dense"),
    ),
    "snapshot-ext": (
        SNAPSHOT,
        FileCost("tests\\test_a.snap", 400, FILLER_TOKEN_COUNT, "code"),
    ),
    "large-data": (
        LARGE_DATA,
        FileCost("data\\rows.json", 9000, LARGE_DATA_TOKENS + 1, "prose"),
    ),
}


@pytest.mark.parametrize(
    "rule,cost", list(NAME_CASES.values()), ids=NAME_CASES.keys()
)
def test_a_backslash_path_is_decided_without_crashing(rule, cost):
    """The portable guarantee for an out-of-contract path: the rule reaches
    a verdict without raising, and if it fires it is its own rule."""
    finding = finding_for(cost)
    assert finding is None or finding.rule is rule


def test_name_rules_follow_the_host_separator_aware_basename():
    """Documents *why* the name-rule verdicts above are platform-defined:
    they read :func:`os.path.basename`, which on Windows also splits on
    ``\\``. On a Windows host a backslash path still fires; the walker never
    produces such a path, so the contract is unchanged."""
    if os.name == "nt":
        cost = NAME_CASES["lockfile"][1]
        assert finding_for(cost) is not None
        assert os.path.basename(cost.path) == ntpath.basename(cost.path)


def test_the_walker_never_emits_a_backslash(tmp_path):
    """The real guarantee underneath all of the above."""
    root = tmp_path / "vendor"
    root.mkdir()
    (root / "lib.py").write_text(FILLER, encoding="utf-8")
    result = walk_repository(str(tmp_path))
    assert [c.path for c in result.files] == ["vendor/lib.py"]


def test_a_dense_file_is_found_whatever_the_separator():
    """The dense rule measures bytes, not names, so it is separator-blind --
    pinned here as the control case the table above must not break."""
    text = "x" * 400
    forward = FileCost("assets/blob.bin", len(text), len(text), "dense")
    back = FileCost("assets\\blob.bin", len(text), len(text), "dense")
    assert finding_for(forward).rule.name == "dense"
    assert finding_for(back).rule.name == "dense"


def test_a_generated_banner_is_read_via_os_path_join_so_both_separators_work(
    tmp_path,
):
    """The generated rule opens ``os.path.join(root, cost.path)``, which is
    correct for a "/"-joined relative path on every platform -- verified
    against a real file rather than reasoning about it."""
    target = tmp_path / "gen" / "out.py"
    target.parent.mkdir()
    target.write_text("// Code generated by protoc. DO NOT EDIT.\n" + FILLER)
    result = walk_repository(str(tmp_path))
    found = {f.path: f.rule.name for f in classify(result)}
    assert found == {"gen/out.py": "generated"}
