"""Which files are spending the budget without earning it.

The walker says what everything costs. This module says what is *waste*, and
that word is doing a lot of work: it is a judgement about someone else's
repository, made by a program that has never read their code. Get it wrong in
the confident direction and the tool tells a data scientist to exclude the
dataset their entire project is about.

So the design is built around not being trusted, in three ways.

**Every rule states its reason.** Not "excluded: generated" but "this file's
first line says `Code generated by protoc-gen-go. DO NOT EDIT.`". A reason a
user can read is a reason a user can reject. Rules whose evidence cannot be
quoted back are not worth having.

**Confidence is a first-class field, and the lowest tier is never acted on.**

- ``certain`` -- the file says what it is, or its name is reserved by a tool
  that generated it. Excluding it cannot lose anything a human wrote.
- ``likely`` -- strong but circumstantial, usually a path convention.
  ``vendor/`` is almost always vendored code; occasionally it is a company
  called Vendor.
- ``possible`` -- the file is expensive and *usually* not read, but it might be
  the entire point of the repository. A large CSV is waste in a web app and is
  the subject matter in an analysis repo, and nothing visible from the file
  system distinguishes them.

:mod:`contextcost.reduce` proposes ``certain`` and ``likely`` automatically and
lists ``possible`` separately for a human to choose. That split is the whole
reason the tier exists; collapsing it would make the tool confidently wrong
exactly where it has the least information.

**A file matches at most one rule.** Several can fire on `vendor/lib.min.js`,
and reporting it three times would inflate the apparent saving threefold --
the same double-count that makes "we found 400 issues" reports meaningless.
The strongest match wins, and ties break toward the rule with the more
specific evidence.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass

from .walk import FileCost, WalkResult

__all__ = ["Finding", "Rule", "RULES", "classify", "rule_named"]

#: Below this, a file is not worth a line in a report even if it is textbook
#: waste. A 40-token lockfile is a rounding error, and a report padded with
#: rounding errors trains the reader to skim past the one line that mattered.
MIN_REPORTABLE_TOKENS = 50

#: A data file above this is expensive enough to raise, even though data is
#: precisely the category where the tool is least able to judge. Roughly one
#: per cent of a 200k context window: small enough to catch real offenders,
#: large enough that ordinary fixtures do not flood the report.
LARGE_DATA_TOKENS = 2000

#: How much of a file to read when looking for a generator banner. Every
#: generator that emits one puts it at the very top -- that is the point of it.
HEADER_BYTES = 2048


@dataclass(frozen=True)
class Rule:
    """One reason a file might not be worth reading."""

    name: str
    #: One line, for the report's section heading.
    summary: str
    #: Why this category is waste, phrased so a reader can disagree with it.
    #: If you cannot write this sentence, the rule does not belong here.
    rationale: str
    #: ``certain``, ``likely`` or ``possible`` -- see the module docstring.
    confidence: str


@dataclass(frozen=True)
class Finding:
    """One file, one rule, and the specific evidence for this file."""

    rule: Rule
    path: str
    tokens: int
    #: What was true of *this* file, quoted where possible. The report prints
    #: it verbatim, because "generated" is an assertion and
    #: "line 1 reads @generated" is a fact.
    evidence: str

    def as_dict(self) -> dict:
        return {
            "path": self.path,
            "tokens": self.tokens,
            "rule": self.rule.name,
            "confidence": self.rule.confidence,
            "evidence": self.evidence,
        }


LOCKFILE = Rule(
    name="lockfile",
    summary="Dependency lockfiles",
    rationale=(
        "A lockfile records resolved versions for a package manager to read. "
        "It is machine-written, often enormous, and an agent that needs a "
        "dependency version can read the manifest instead."
    ),
    confidence="certain",
)

GENERATED = Rule(
    name="generated",
    summary="Generated files that say so",
    rationale=(
        "The file carries a generator banner. Whatever an agent might learn "
        "from it is stated more compactly in the schema or template it was "
        "generated from, and edits to it are overwritten by the next build."
    ),
    confidence="certain",
)

MINIFIED = Rule(
    name="minified",
    summary="Minified or bundled output",
    rationale=(
        "Minified content costs far more per unit of meaning than the source "
        "it came from -- no line breaks, no names, and a tokenizer splitting "
        "nearly every character. The readable original is in the repository."
    ),
    confidence="certain",
)

DENSE = Rule(
    name="dense",
    summary="Machine-written dense content",
    rationale=(
        "The content is long unbroken runs of characters: hashes, base64 "
        "payloads, embedded blobs, manifest entries. It costs roughly twice "
        "as many tokens per character as source code does, and it is written "
        "for a program to parse rather than a person to read. Unlike the "
        "minified rule this is a measurement of the bytes, not a claim about "
        "where the file came from -- so it says the file is expensive and "
        "machine-shaped, not that a readable original exists elsewhere."
    ),
    confidence="likely",
)

VENDORED = Rule(
    name="vendored",
    summary="Vendored third-party code",
    rationale=(
        "Third-party source committed into the tree. It is somebody else's "
        "code, it is on the package index, and it is rarely what a question "
        "about this repository is about."
    ),
    confidence="likely",
)

BUILD_OUTPUT = Rule(
    name="build-output",
    summary="Build output",
    rationale=(
        "Compiled or bundled artefacts, reproducible from the source next to "
        "them. Usually these are ignored already; when they are not, they are "
        "typically the largest thing in the repository."
    ),
    confidence="likely",
)

SNAPSHOT = Rule(
    name="snapshot",
    summary="Test snapshots and recorded fixtures",
    rationale=(
        "Snapshots are written by the test runner and compared byte for byte. "
        "They are evidence that behaviour did not change, not an explanation "
        "of what the behaviour is."
    ),
    confidence="likely",
)

LARGE_DATA = Rule(
    name="large-data",
    summary="Large data files",
    rationale=(
        "Expensive, and usually read by code rather than by a reader. But "
        "this is the one category the file system cannot settle: in an "
        "analysis repository the data is the subject. Decide this one "
        "yourself -- it is never excluded automatically."
    ),
    confidence="possible",
)

#: Ordered strongest-evidence first. :func:`classify` takes the first match,
#: so a minified file inside `vendor/` is reported as minified -- the more
#: specific fact about it.
RULES = (
    LOCKFILE,
    GENERATED,
    MINIFIED,
    DENSE,
    VENDORED,
    BUILD_OUTPUT,
    SNAPSHOT,
    LARGE_DATA,
)

_CONFIDENCE_ORDER = {"certain": 0, "likely": 1, "possible": 2}

#: Exact filenames. Matching on the name is safe here because every one of
#: these is reserved by a package manager that writes it.
_LOCKFILES = frozenset(
    {
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "bun.lockb",
        "poetry.lock",
        "pipfile.lock",
        "pdm.lock",
        "uv.lock",
        "cargo.lock",
        "composer.lock",
        "gemfile.lock",
        "go.sum",
        "mix.lock",
        "pubspec.lock",
        "packages.lock.json",
        "conan.lock",
        "flake.lock",
        "podfile.lock",
    }
)

#: Directory names that mean "this came from somewhere else".
_VENDOR_DIRS = frozenset(
    {
        "vendor",
        "vendored",
        "third_party",
        "thirdparty",
        "node_modules",
        "bower_components",
        "godeps",
        "external",
    }
)

#: Directory names that mean "this was produced from the source beside it".
#: `build` and `out` are also plausible source directory names, which is why
#: this rule is `likely` rather than `certain`.
_BUILD_DIRS = frozenset(
    {
        "dist",
        "build",
        "target",
        "out",
        ".next",
        ".nuxt",
        "_build",
        "obj",
        "bin",
        "coverage",
        "htmlcov",
        "site-packages",
    }
)

_SNAPSHOT_DIRS = frozenset(
    {"__snapshots__", "snapshots", "cassettes", "__recordings__"}
)

_DATA_SUFFIXES = frozenset(
    {
        ".csv",
        ".tsv",
        ".json",
        ".jsonl",
        ".ndjson",
        ".parquet",
        ".sql",
        ".xml",
        ".yaml",
        ".yml",
        ".txt",
        ".log",
    }
)

#: Banners real generators emit, as word-boundary patterns.
#:
#: These were plain substrings once, and `"generated file"` matched the prose
#: phrase "chatgpt-generated files" in a hand-written notices file -- a false
#: positive at `certain` confidence, the single worst outcome this module can
#: produce. Two things went wrong and both are fixed here: the marker was loose
#: enough to match inside another word, and it was searched for anywhere in the
#: first two kilobytes rather than in the banner region where generators
#: actually write.
#:
#: So: word boundaries, no bare "generated", and only the first few lines.
_GENERATOR_PATTERNS = (
    re.compile(r"\bcode generated by\b", re.IGNORECASE),
    re.compile(r"@generated\b", re.IGNORECASE),
    re.compile(r"\bdo not edit\b", re.IGNORECASE),
    re.compile(r"\bauto-?generated\b", re.IGNORECASE),
    re.compile(r"\bautomatically generated\b", re.IGNORECASE),
    re.compile(r"\bthis file (?:is|was) generated\b", re.IGNORECASE),
    re.compile(r"\bgenerated by the protocol buffer compiler\b", re.IGNORECASE),
)

#: Generator banners sit at the very top -- that is the entire point of them.
#: Anything further down is prose that happens to use the word.
HEADER_LINES = 10

_MINIFIED_NAME = re.compile(r"\.(min|bundle|chunk)\.(js|css|mjs|cjs)$", re.IGNORECASE)


def rule_named(name: str) -> Rule:
    """Look a rule up by name, for the CLI's ``--ignore-rule``."""
    for rule in RULES:
        if rule.name == name:
            return rule
    raise KeyError(name)


def _segments(path: str) -> list[str]:
    return [part.lower() for part in path.split("/")[:-1]]


def _read_header(root: str, relative: str) -> list[str]:
    """The first :data:`HEADER_LINES` lines of a file, or ``[]``."""
    try:
        with open(os.path.join(root, relative), "rb") as handle:
            raw = handle.read(HEADER_BYTES)
    except OSError:
        # The walk already succeeded on this file, so a failure here means it
        # changed underneath us. Finding no banner is the safe answer: it
        # means the file is kept.
        return []
    return raw.decode("utf-8", errors="replace").splitlines()[:HEADER_LINES]


def _generator_banner(root: str, cost: FileCost) -> str | None:
    """The generator banner in this file's opening lines, quoted, or ``None``."""
    for line in _read_header(root, cost.path):
        for pattern in _GENERATOR_PATTERNS:
            found = pattern.search(line)
            if found is None:
                continue
            # Quote the line, not just the marker: "do not edit" on its own
            # reads like an assertion by this tool rather than a quotation.
            text = line.strip().lstrip("#/*!-; \t").strip()
            at = text.lower().find(found.group().lower())
            # Window the quote around the marker rather than taking the first
            # 90 characters. A long line whose marker sat past that cutoff
            # produced evidence with no marker visible in it, and a quotation
            # that does not contain the thing it is evidence for is worse than
            # none: it looks checkable and is not.
            if at > 60:
                text = "..." + text[at - 20 :]
            return f'header reads "{text[:90].strip()}"'
    return None


def _match(root: str, cost: FileCost) -> Finding | None:
    """The single strongest rule for one file, or ``None`` if it earns its keep."""
    name = os.path.basename(cost.path).lower()
    segments = _segments(cost.path)

    if name in _LOCKFILES:
        return Finding(
            LOCKFILE, cost.path, cost.tokens, f"{name} is written by a package manager"
        )

    banner = _generator_banner(root, cost)
    if banner is not None:
        return Finding(GENERATED, cost.path, cost.tokens, banner)

    if _MINIFIED_NAME.search(name):
        return Finding(
            MINIFIED, cost.path, cost.tokens, "named as minified or bundled output"
        )
    if cost.kind == "dense":
        # Deliberately a separate rule from `minified`, at lower confidence.
        # Both fire on the same measurement, but "this is minified output"
        # asserts a readable original exists somewhere -- which is false for
        # the JSON manifests this fires on most often, and reporting a false
        # reason for a true conclusion is the failure this module is built to
        # avoid. Found by running against a real repository, where two
        # manifests were confidently described as minified JavaScript.
        return Finding(
            DENSE, cost.path, cost.tokens, "content is long unbroken runs of characters"
        )

    for segment in segments:
        if segment in _VENDOR_DIRS:
            return Finding(
                VENDORED, cost.path, cost.tokens, f"inside a directory named {segment}/"
            )
    for segment in segments:
        if segment in _SNAPSHOT_DIRS:
            return Finding(
                SNAPSHOT, cost.path, cost.tokens, f"inside a directory named {segment}/"
            )
    if name.endswith(".snap") or name.endswith(".ambr"):
        return Finding(
            SNAPSHOT, cost.path, cost.tokens, "a test runner's snapshot file"
        )
    for segment in segments:
        if segment in _BUILD_DIRS:
            return Finding(
                BUILD_OUTPUT,
                cost.path,
                cost.tokens,
                f"inside a directory named {segment}/",
            )

    if cost.tokens >= LARGE_DATA_TOKENS and cost.extension in _DATA_SUFFIXES:
        share_note = f"{cost.tokens:,} tokens in a single {cost.extension} file"
        return Finding(LARGE_DATA, cost.path, cost.tokens, share_note)

    return None


def classify(result: WalkResult) -> list[Finding]:
    """Every file in ``result`` that some rule says is not worth reading.

    Sorted by cost, because the report's job is to put the expensive decision
    first. Two files matching different rules are still ranked against each
    other -- the reader wants to know what to cut, not what category it is in.
    """
    findings = []
    for cost in result.text_files:
        if cost.tokens < MIN_REPORTABLE_TOKENS:
            continue
        finding = _match(result.root, cost)
        if finding is not None:
            findings.append(finding)
    findings.sort(key=lambda f: (-f.tokens, f.path))
    return findings


def by_rule(findings: list[Finding]) -> dict[str, list[Finding]]:
    """Group findings by rule name, strongest confidence first."""
    grouped: dict[str, list[Finding]] = {}
    for finding in findings:
        grouped.setdefault(finding.rule.name, []).append(finding)
    return dict(
        sorted(
            grouped.items(),
            key=lambda kv: (
                _CONFIDENCE_ORDER[kv[1][0].rule.confidence],
                -sum(f.tokens for f in kv[1]),
            ),
        )
    )
