"""Generate the README figures, and check they still match the code.

Two rules shape this file.

**The example repository is generated, not committed.** Checking in a fixture
repository to illustrate a tool that measures repository bloat would be funny
once and embarrassing afterwards. It is built deterministically in a temporary
directory, measured, and thrown away, so the figures are reproducible on any
machine and in CI without carrying the weight.

**The numbers in the README come from running the tool, never from typing.** A
README that quotes a saving the code no longer produces is the exact failure
this project argues against, and it is the easiest one to commit by accident.
``--check`` regenerates everything and fails if the committed README differs,
so CI catches a stale number the same way it catches a failing test.

Usage:
    python docs/build_docs.py           # regenerate figures and README
    python docs/build_docs.py --check   # fail if anything is out of date
"""

from __future__ import annotations

import os
import sys
import tempfile

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src")
)

from contextcost.classify import classify  # noqa: E402
from contextcost.estimate import ERROR_BOUND  # noqa: E402
from contextcost.reduce import reduce_repository  # noqa: E402
from contextcost.walk import walk_repository  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

#: House palette. Dark background so the figures sit next to terminal output
#: in a README without one of them looking like a screenshot of the other.
INK = (16, 18, 24)
PAPER = (232, 234, 240)
MUTED = (120, 126, 142)
GRID = (44, 48, 60)
WASTE = (232, 118, 92)
KEPT = (104, 172, 216)
SAVED = (124, 196, 140)

BEGIN = "<!-- BEGIN GENERATED -->"
END = "<!-- END GENERATED -->"


def example_repository(root: str) -> None:
    """Write a small, ordinary web project: some source, and the usual ballast.

    Deliberately unremarkable. The point of the figure is that a repository
    nobody would call bloated still spends most of its budget on files no
    reader ever opens.
    """
    files = {
        "package.json": '{\n  "name": "example",\n  "version": "1.0.0"\n}\n',
        "README.md": "# example\n\nA small web project.\n"
        + ("Documentation prose. " * 400),
        "src/app.js": "export function render(state) {\n  return state.items.map(String);\n}\n"
        * 220,
        "src/store.js": "export const store = { items: [] };\n" * 300,
        "src/router.js": "export const routes = { '/': 'home' };\n" * 260,
        "src/api/client.js": "export async function get(url) {\n"
        "  return fetch(url).then((r) => r.json());\n}\n" * 150,
        "src/util/format.js": "export const format = (n) => n.toFixed(2);\n" * 240,
        "src/components/list.js": "export const List = ({items}) => items.map((i) => i.name);\n"
        * 210,
        "tests/app.test.js": "test('renders', () => { expect(render({})).toEqual([]); });\n"
        * 180,
        "tests/store.test.js": "test('stores', () => { expect(store.items).toEqual([]); });\n"
        * 160,
        # The ballast.
        "package-lock.json": '{"name":"example","lockfileVersion":3,"packages":{'
        + ",".join(
            f'"node_modules/pkg{n}":{{"version":"1.0.{n}","resolved":"https://registry.example/pkg{n}"}}'
            for n in range(260)
        )
        + "}}\n",
        "dist/bundle.min.js": ";".join(
            f"function a{n}(b,c){{return b+c*{n}}}" for n in range(430)
        )
        + "\n",
        "vendor/legacy/widget.js": "// vendored widget\nvar widget = {};\n" * 120,
        "vendor/legacy/helpers.js": "var helpers = {};\n" * 150,
        "tests/__snapshots__/app.test.js.snap": "exports[`renders 1`] = `\n<div>item</div>\n`;\n"
        * 80,
        "src/generated/schema.js": "// Code generated by schema-gen. DO NOT EDIT.\n"
        + "export const Schema = { field: 'value' };\n" * 90,
    }
    for relative, text in files.items():
        path = os.path.join(root, relative.replace("/", os.sep))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)


def _font(size: int):
    from PIL import ImageFont

    for name in (
        "DejaVuSans.ttf",
        "arial.ttf",
        "Helvetica.ttc",
        "LiberationSans-Regular.ttf",
    ):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    try:
        return ImageFont.load_default(size=size)
    except TypeError:  # Pillow < 10.1
        return ImageFont.load_default()


def figure_breakdown(walk, findings, path: str) -> None:
    """Cost per top-level directory, with the wasteful share marked."""
    from PIL import Image, ImageDraw

    width, row, top = 900, 46, 92
    totals = walk.by_directory()
    wasteful = {f.path for f in findings}
    height = top + row * len(totals) + 40

    image = Image.new("RGB", (width, height), INK)
    draw = ImageDraw.Draw(image)
    title, label, small = _font(23), _font(17), _font(14)

    draw.text((34, 28), "Where the context budget goes", font=title, fill=PAPER)
    draw.text(
        (34, 60),
        f"{walk.tokens:,} tokens to read this repository  "
        f"(estimated, ±{ERROR_BOUND:.0%})",
        font=small,
        fill=MUTED,
    )

    biggest = max(totals.values()) if totals else 1
    bar_left, bar_width = 210, 560
    for index, (name, tokens) in enumerate(totals.items()):
        y = top + index * row
        draw.text((34, y + 8), name[:20], font=label, fill=PAPER)

        waste = sum(
            c.tokens
            for c in walk.text_files
            if c.path in wasteful
            and (c.path.split("/")[0] if "/" in c.path else "(root)") == name
        )
        full = int(bar_width * tokens / biggest)
        draw.rectangle([bar_left, y + 6, bar_left + full, y + 30], fill=KEPT)
        if waste:
            draw.rectangle(
                [bar_left, y + 6, bar_left + int(full * waste / tokens), y + 30],
                fill=WASTE,
            )
        draw.text(
            (bar_left + bar_width + 18, y + 8), f"{tokens:,}", font=label, fill=PAPER
        )

    legend = height - 28
    draw.rectangle([34, legend, 50, legend + 13], fill=WASTE)
    draw.text((58, legend - 2), "not worth reading", font=small, fill=MUTED)
    draw.rectangle([214, legend, 230, legend + 13], fill=KEPT)
    draw.text((238, legend - 2), "worth reading", font=small, fill=MUTED)
    image.save(path)


def figure_saving(reduction, path: str) -> None:
    """Before and after, side by side, labelled as a measurement."""
    from PIL import Image, ImageDraw

    width, height = 900, 300
    image = Image.new("RGB", (width, height), INK)
    draw = ImageDraw.Draw(image)
    title, label, small, big = _font(23), _font(17), _font(14), _font(34)

    draw.text((34, 28), "What the proposal actually saves", font=title, fill=PAPER)
    draw.text(
        (34, 60),
        "Measured by walking the repository again, not by subtracting what was dropped.",
        font=small,
        fill=MUTED,
    )

    bar_left, bar_width = 150, 620
    scale = bar_width / reduction.before if reduction.before else 0

    draw.text((34, 118), "before", font=label, fill=MUTED)
    draw.rectangle([bar_left, 112, bar_left + bar_width, 146], fill=GRID)
    draw.rectangle([bar_left, 112, bar_left + bar_width, 146], fill=WASTE)
    draw.text(
        (bar_left + bar_width + 14, 118),
        f"{reduction.before:,}",
        font=label,
        fill=PAPER,
    )

    after_width = int(reduction.after * scale)
    draw.text((34, 178), "after", font=label, fill=MUTED)
    draw.rectangle([bar_left, 172, bar_left + bar_width, 206], fill=GRID)
    draw.rectangle([bar_left, 172, bar_left + after_width, 206], fill=SAVED)
    draw.text(
        (bar_left + after_width + 14, 178),
        f"{reduction.after:,}",
        font=label,
        fill=PAPER,
    )

    draw.text((34, 236), f"{reduction.share:.0%} saved", font=big, fill=SAVED)
    draw.text(
        (240, 248),
        f"{reduction.saved:,} tokens, across {len(reduction.excluded)} files",
        font=small,
        fill=MUTED,
    )
    image.save(path)


def generated_section(walk, reduction, findings) -> str:
    """The block of the README that is rebuilt from a real run."""
    rows = []
    for finding in reduction.findings[:5]:
        rows.append(
            f"| `{finding.path}` | {finding.tokens:,} | {finding.rule.name} "
            f"| {finding.rule.confidence} |"
        )
    deferred = ""
    if reduction.deferred:
        names = ", ".join(f"`{f.path}`" for f in reduction.deferred[:3])
        deferred = (
            f"\n{len(reduction.deferred)} further file(s) — {names} — are listed but "
            "**not** excluded, because nothing visible from the file system says "
            "whether they are fixtures or the subject of the work.\n"
        )

    return f"""{BEGIN}

### On an ordinary small project

The example below is generated by `docs/build_docs.py`: a small web project
with some source, a lockfile, a bundle, a vendored widget and a snapshot file.
Nobody would call it bloated.

![Where the context budget goes](breakdown.png)

**{walk.tokens:,} tokens** to read {len(walk.text_files)} text files
(estimated, ±{ERROR_BOUND:.0%} — see below for why there is no tokenizer).

| file | tokens | rule | confidence |
| --- | ---: | --- | --- |
{chr(10).join(rows)}

![What the proposal actually saves](saving.png)

Excluding those leaves **{reduction.after:,} tokens — a {reduction.share:.0%}
reduction**, and that number is the difference between two walks of the
repository, not a sum of what was dropped.
{deferred}
{END}"""


def build(check: bool) -> int:
    with tempfile.TemporaryDirectory() as workspace:
        example_repository(workspace)
        walk = walk_repository(workspace)
        findings = classify(walk)
        reduction = reduce_repository(workspace)

        breakdown = os.path.join(HERE, "breakdown.png")
        saving = os.path.join(HERE, "saving.png")
        if check:
            # Render to a scratch location so --check never mutates the tree.
            breakdown = os.path.join(workspace, "breakdown.png")
            saving = os.path.join(workspace, "saving.png")
        figure_breakdown(walk, findings, breakdown)
        figure_saving(reduction, saving)

        section = generated_section(walk, reduction, findings)

    readme_path = os.path.join(ROOT, "README.md")
    with open(readme_path, encoding="utf-8") as handle:
        readme = handle.read()

    if BEGIN not in readme or END not in readme:
        print("README.md is missing the generated markers", file=sys.stderr)
        return 1

    head, _, rest = readme.partition(BEGIN)
    _, _, tail = rest.partition(END)
    rebuilt = head + section + tail

    if check:
        if rebuilt != readme:
            print(
                "README.md is out of date. Run: python docs/build_docs.py",
                file=sys.stderr,
            )
            return 1
        print("README.md is up to date.")
        return 0

    with open(readme_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rebuilt)
    print(
        f"Wrote README.md, docs/breakdown.png and docs/saving.png "
        f"({reduction.before:,} -> {reduction.after:,} tokens)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(build("--check" in sys.argv))
